# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish Docker image

on:
  release:
    types: [published]

env:
  OTP_VERSION: '24.3.4.1'
  ELIXIR_VERSION: '1.13.4'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    env:
      RELEASE_VERSION: 4.1.4
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: blockscout/blockscout
      
      - name: Build & Push Docker image
        run: |
          docker buildx build \
          -t blockscout/blockscout:latest \
          -t blockscout/blockscout:${{ env.RELEASE_VERSION }} \
          -f ./docker/Dockerfile \
          --build-arg CACHE_EXCHANGE_RATES_PERIOD="" \
          --build-arg DISABLE_READ_API="false" \
          --build-arg API_PATH="/" \
          --build-arg NETWORK_PATH="/" \
          --build-arg DISABLE_WEBAPP="false" \
          --build-arg DISABLE_WRITE_API="false" \
          --build-arg CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER="" \
          --build-arg WOBSERVER_ENABLED="false" \
          --build-arg ADMIN_PANEL_ENABLED="" \
          --build-arg CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL="" \
          --build-arg SOCKET_ROOT="" \
          --build-arg CHAIN_ID="" \
          --build-arg JSON_RPC="" \
          --build-arg SUBNETWORK="" \
          --build-arg COIN_NAME="" \
          --push --platform=linux/arm64,linux/amd64 .
